FROM rust:latest

RUN apt-get update && \
    apt-get install -y gcc-aarch64-linux-gnu libssl-dev && \
    rm -rf /var/lib/apt/lists/* && \
    rustup target add aarch64-unknown-linux-gnu && \
    mkdir /output

WORKDIR /build

COPY . .

RUN cargo build --release --target aarch64-unknown-linux-gnu && \
    cp /build/target/aarch64-unknown-linux-gnu/release/qb-och /output/qb-och